### ISSUE TITLE
Cannot verify new account

### ISSUE THREAD

**Issue by IsaacReefman** [onetimesecret/onetimesecret#155]
Some of the comments on another issue seem to be experiencing this, but it seemed different to the actual title: I never recieve the verification email for a new account. I'm interested in using the api to send out credentials to new users created in my web app (without requiring anything more of my management level users who add new users) but I can't even get past the hurdle of creating an account...

**Comment by dwesterman** [comment]
I have had this problem for a while, too. It seems their mailer isn't working properly, based on some of the other comments.

Hopefully someone who maintains this will be able to respond soon. I, too, am wanting to use this to distribute credentials to users in a secure way.

**Comment by delano** [comment]
Thanks for the reports. There was an issue with the email service. It's fixed now. 

We don't resend verification emails so email me at info@onetimesecret.com with the address.

**Comment by glauber-experian** [comment]
Same... new account created, never received the verification email. I will email info@onetimesecret.com

**Comment by dclark-techno** [comment]
This issue is still happening in 2024, I have emailed info@onetimesecret.com for help. I'm not seeing that email on the website so hope other users are able to find the address.
